# Generated by Django 5.1.7 on 2025-04-28 03:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000)),
                ('descrição', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('completa', 'Completa')], default='pendente', max_length=20)),
                ('urgencia', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Objetivos', to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descrição', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluída', 'Concluída')], default='pendente', max_length=20)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='objetivos.objetivo')),
            ],
        ),
    ]
