# Generated by Django 5.1.7 on 2025-04-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_subtarefa_objetivo_delete_objetivo_and_more'),
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Objetivos', to='login.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
