# Generated by Django 5.1.7 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_grupo', models.CharField(max_length=1000, unique=True)),
                ('Qtd_membros_grupo', models.PositiveIntegerField()),
                ('Senha_grupo', models.CharField(max_length=100)),
                ('Participantes', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
