# Generated by Django 5.1.7 on 2025-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0002_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes_grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grupos', models.CharField(max_length=1000)),
                ('nome_participantes', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='Participantes',
        ),
    ]
