# Generated by Django 5.1.7 on 2025-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0003_participantes_grupos_remove_grupos_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupos',
            name='Qtd_membros_grupo',
        ),
    ]
