# Generated by Django 5.1.7 on 2025-04-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtarefa',
            name='objetivo',
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
        migrations.DeleteModel(
            name='Subtarefa',
        ),
    ]
